server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3307/oauth2?useSSL=false
    username: admin
    password: Alamoud!
    
logging:
  level:
    org.springframework.security: TRACE
      
security:
#  basic:
#    enabled: false
  user:
    name: user
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/